set guicursor= 
set relativenumber
set nohlsearch
set hidden
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set nowrap
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set termguicolors
set scrolloff=5
set signcolumn=yes
set isfname+=@-@
set cmdheight=1
set updatetime=300
set shortmess+=c
set colorcolumn=80
set splitright
